### ISSUE TITLE
Add more explanation about CCSync and its components 

### ISSUE THREAD

**Issue by its-me-abhishek** [its-me-abhishek/ccsync-docs#1]
- Document more about the environment variables

**Comment by sternj** [comment]
So in this case, what is the difference between `origin` from [the flutter app](https://github.com/CCExtractor/taskwarrior-flutter/issues/347#issuecomment-2221099252) and `CONTAINER_ORIGIN` in this container environment?

**Comment by its-me-abhishek** [comment]
the `origin` in the flutter app is a placeholder (atleast for now) so it can be anything but null as we need a parameter.


The CONTAINER_ORIGIN refers to the taskchampion sync server containers' url that you're using to sync across all your devices.

**Comment by its-me-abhishek** [comment]
I've added comments about the variables in the index.md in the latest commit.

**Comment by SGI-CAPP-AT2** [comment]
Title: Getting Errors while setup

Hey @its-me-abhishek ,
I have done setup of ccsync and sync-server.
Also I have done with the installation of taskwarrior 
following containers are running
```
[root@ShGI ccsync]# docker-compose up
[+] Running 3/0
 ✔ Container ccsync-syncserver-1  Running                                                                                         0.0s 
 ✔ Container ccsync-backend-1     Running                                                                                         0.0s 
 ✔ Container ccsync-frontend-1    Running                                                                                         0.0s 
Attaching to backend-1, frontend-1, syncserver-1
```
but when I add task or sync tasks its returning internal server error
I have also done with the setup of taskwarrior as
```
[root@ShGI ccsync]# task --version
3.2.0
[root@ShGI ccsync]# task config sync.encryption_secret ZZZZaee9076288e08ea13e3508580a99c1bdc120f8bae8fd5c0afb22ee1bXXXX
Are you sure you want to add 'sync.encryption_secret' with a value of 'ZZZZaee9076288e08ea13e3508580a99c1bdc120f8bae8fd5c0afb22ee1bXXXX'? (yes/no) yes
Config file /root/.taskrc modified.
[root@ShGI ccsync]# task config sync.server.origin http://localhost:8080/
Are you sure you want to add 'sync.server.origin' with a value of 'http://localhost:8080/'? (yes/no) yes
Config file /root/.taskrc modified.
[root@ShGI ccsync]# task config sync.server.client_id d542def4-XXXX-34a4-bd44-27efd5b71XXX
Are you sure you want to add 'sync.server.client_id' with a value of 'd542def4-XXXX-34a4-bd44-27efd5b71XXX'? (yes/no) yes
Config file /root/.taskrc modified.
[root@ShGI ccsync]# task sync init
sync.server.origin is deprecated. Use sync.server.url instead.
Syncing with sync server at http://localhost:8080/
```

getting following errors in react frontend
![image](https://github.com/user-attachments/assets/cf137ac2-458e-4c2c-9a52-4026c2ce8048)
![image](https://github.com/user-attachments/assets/ee3997ce-f597-4d28-8f99-a0f8adea0bb6)

I dont know if this is correct place to ask for help as there is no slack channel for ccsync.

**Comment by its-me-abhishek** [comment]
> sync.server.origin is deprecated. Use sync.server.url instead.

have u tried working on this? as I am unaware if this has recently got deprecated or not... 
might be a simple fix if you could work it out on the Docker shell

**Comment by SGI-CAPP-AT2** [comment]
I have tried both `sync.server.origin` and also `sync.server.url` but still Internal Server Error

**Comment by SGI-CAPP-AT2** [comment]
Sorry, I didn't tried on docker shell instead i was trying on my WSL.
Confused by this :
![image](https://github.com/user-attachments/assets/c67d90a5-035c-4d76-985c-95480b8e46b4)
Sorry about that

**Comment by its-me-abhishek** [comment]
for these common issues, I think that the official Slack's #taskwarrior-flutter channel should suffice, until a new channel is created dedicated to CCSync
